# modules/product/aurora.tf
#
# Aurora PostgreSQL building block — conditional deployment.
# The module is self-sufficient: it discovers VPC, subnets, and KMS internally.
# The compositor passes through identity variables and block-specific config.

module "aurora" {
  count  = var.aurora_enabled ? 1 : 0
  source = "../database/aurora-postgresql"

  # ── Identity (common) ───────────────────────────────────────────────────────
  aws_region     = var.aws_region
  service        = var.service
  workload       = var.workload
  funcionalidad  = var.funcionalidad
  ambiente       = var.ambiente
  aws_account_id = var.aws_account_id

  # ── Engine ──────────────────────────────────────────────────────────────────
  engine_version = var.aurora_config.engine_version
  db_family      = var.aurora_config.db_family
  database_name  = var.aurora_config.database_name

  # ── Admin credential (from BeyondTrust) ─────────────────────────────────────
  master_username = var.aurora_config.master_username
  master_password = var.master_password

  # ── Compute model ──────────────────────────────────────────────────────────
  serverless         = var.aurora_config.serverless
  serverless_min_acu = var.aurora_config.min_acu
  serverless_max_acu = var.aurora_config.max_acu
  instance_class     = var.aurora_config.instance_class
  storage_type       = var.aurora_config.storage_type
  multi_az           = var.aurora_config.multi_az
  instances          = var.aurora_config.instances

  # ── Network access ─────────────────────────────────────────────────────────
  allowed_security_group_ids = var.aurora_config.allowed_security_group_ids
  allowed_cidrs              = var.aurora_config.allowed_cidrs

  # ── Backups / lifecycle ─────────────────────────────────────────────────────
  backup_retention_period = var.aurora_config.backup_retention_period
  deletion_protection     = var.aurora_config.deletion_protection
  apply_immediately       = var.aurora_config.apply_immediately

  # ── Observability ───────────────────────────────────────────────────────────
  performance_insights_enabled = var.aurora_config.performance_insights_enabled

  # ── Global Database (DR) ────────────────────────────────────────────────────
  enable_global_database    = var.aurora_config.enable_global_database
  global_cluster_identifier = var.aurora_config.global_cluster_identifier

  # ── KMS ─────────────────────────────────────────────────────────────────────
  kms_key_alias                 = var.aurora_config.kms_key_alias
  kms_key_arn                   = var.aurora_config.kms_key_arn
  cloudwatch_logs_kms_key_alias = var.aurora_config.cloudwatch_logs_kms_key_alias
  cloudwatch_logs_kms_key_arn   = var.aurora_config.cloudwatch_logs_kms_key_arn

  # ── KMS grants ───────────────────────────────────────────────────────────────
  # NOTE: IRSA roles that need KMS access include kms:Decrypt in their own
  # inline policies (generated by the compositor). kms_consumer_role_arns is
  # reserved for EXTERNAL consumers (lambda, ECS) not managed by this module.
  # Passing IRSA role_arns here would create a circular dependency:
  #   aurora.kms_consumer_role_arns → irsa.role_arns → aurora.outputs
  kms_consumer_role_arns = {}

  # ── Mandatory tags ──────────────────────────────────────────────────────────
  aplicacion          = var.aplicacion
  propietario_recurso = var.propietario_recurso
  producto            = var.producto
  centro_costo        = var.centro_costo
  extra_tags          = var.extra_tags
}
