# modules/product/redis.tf
#
# ElastiCache Serverless building block — conditional deployment.
# The module is self-sufficient: it discovers VPC, subnets, and KMS internally.

module "redis" {
  count  = var.redis_enabled ? 1 : 0
  source = "../database/elasticache-serverless"

  # ── Identity (common) ───────────────────────────────────────────────────────
  aws_region        = var.aws_region
  service           = var.service
  vpc_discovery_tag = var.vpc_discovery_tag
  workload          = var.workload
  funcionalidad     = var.funcionalidad
  ambiente          = var.ambiente
  aws_account_id    = var.aws_account_id

  # ── Engine ──────────────────────────────────────────────────────────────────
  engine               = var.redis_config.engine
  major_engine_version = var.redis_config.major_engine_version

  # ── Usage limits (FinOps guard-rails) ───────────────────────────────────────
  max_ecpu_per_second = var.redis_config.max_ecpu_per_second
  max_data_storage_gb = var.redis_config.max_data_storage_gb

  # ── Snapshots ───────────────────────────────────────────────────────────────
  snapshot_retention_days = var.redis_config.snapshot_retention_days
  daily_snapshot_time     = var.redis_config.daily_snapshot_time

  # ── Network access ─────────────────────────────────────────────────────────
  allowed_security_group_ids = var.redis_config.allowed_security_group_ids
  allowed_cidrs              = var.redis_config.allowed_cidrs

  # ── User group (IAM auth) ───────────────────────────────────────────────────
  user_group_id = var.redis_config.user_group_id

  # ── KMS ─────────────────────────────────────────────────────────────────────
  kms_key_alias = var.redis_config.kms_key_alias
  kms_key_arn   = var.redis_config.kms_key_arn

  # ── CloudWatch Logs (managed log groups) ────────────────────────────────────
  cloudwatch_logs_kms_key_alias = var.redis_config.cloudwatch_logs_kms_key_alias
  cloudwatch_logs_kms_key_arn   = var.redis_config.cloudwatch_logs_kms_key_arn

  # ── KMS grants ───────────────────────────────────────────────────────────────
  # NOTE: IRSA roles that need KMS access include kms:Decrypt in their own
  # inline policies (generated by the compositor). Passing IRSA role_arns
  # here would create a circular dependency.
  kms_consumer_role_arns = {}

  # ── Mandatory tags ──────────────────────────────────────────────────────────
  aplicacion          = var.aplicacion
  propietario_recurso = var.propietario_recurso
  producto            = var.producto
  centro_costo        = var.centro_costo
  extra_tags          = var.extra_tags
}
