# modules/product/sqs.tf
#
# SQS building block — conditional deployment.
# SQS is a managed service — no VPC discovery needed.
# The module discovers KMS internally via alias.

module "sqs" {
  count  = var.sqs_enabled ? 1 : 0
  source = "../messaging/sqs"

  # ── Identity (common) ───────────────────────────────────────────────────────
  aws_region     = var.aws_region
  service        = var.service
  workload       = var.workload
  funcionalidad  = var.funcionalidad
  ambiente       = var.ambiente
  aws_account_id = var.aws_account_id

  # ── Queues (map-driven) ─────────────────────────────────────────────────────
  queues = var.sqs_queues

  # ── KMS ─────────────────────────────────────────────────────────────────────
  kms_key_alias                     = var.sqs_config.kms_key_alias
  kms_key_arn                       = var.sqs_config.kms_key_arn
  kms_data_key_reuse_period_seconds = var.sqs_config.kms_data_key_reuse_period_seconds

  # ── KMS grants ───────────────────────────────────────────────────────────────
  # NOTE: IRSA roles that need KMS access include kms:Decrypt/kms:GenerateDataKey
  # in their own inline policies (generated by the compositor). Passing
  # IRSA role_arns here would create a circular dependency.
  kms_consumer_role_arns = {}

  # ── Mandatory tags ──────────────────────────────────────────────────────────
  aplicacion          = var.aplicacion
  propietario_recurso = var.propietario_recurso
  producto            = var.producto
  centro_costo        = var.centro_costo
  extra_tags          = var.extra_tags
}
