# modules/product/variables.tf
#
# Inputs for the product compositor module.
# Combines *_enabled booleans and *_config objects to drive which building
# blocks are deployed. Common identity/tag variables are passed through to
# all child modules uniformly.
#
# The dev (via terragrunt.hcl generated by Port.io) only sees the blocks
# they requested — disabled blocks are NOT present in their file.

# ═══════════════════════════════════════════════════════════════════════════════
# CORE IDENTITY (passed through to ALL building blocks)
# ═══════════════════════════════════════════════════════════════════════════════

variable "aws_region" {
  description = "AWS region where resources will be created."
  type        = string
  default     = "us-east-1"

  validation {
    condition     = contains(["us-east-1", "us-east-2"], var.aws_region)
    error_message = "aws_region must be us-east-1 (primary) or us-east-2 (DR)."
  }
}

variable "service" {
  description = "OU name (lowercase) used for VPC discovery via tag 'ou'. Passed from orchestrator extra_vars."
  type        = string

  validation {
    condition     = can(regex("^[a-z0-9-]+$", var.service))
    error_message = "service must be lowercase alphanumeric and hyphens only."
  }
}

variable "workload" {
  description = "Short workload name (e.g. 'pagos-core', 'notificaciones'). Used in resource naming."
  type        = string

  validation {
    condition     = can(regex("^[a-z0-9-]{3,30}$", var.workload))
    error_message = "workload must be 3-30 chars, lowercase alphanumeric and hyphens only."
  }
}

variable "funcionalidad" {
  description = "Specific purpose within the workload. Used in naming: {tipo}-aw-{region}-{workload}-{funcionalidad}-{ambiente}."
  type        = string

  validation {
    condition     = can(regex("^[a-z0-9-]{3,30}$", var.funcionalidad))
    error_message = "funcionalidad must be 3-30 chars, lowercase alphanumeric and hyphens only."
  }
}

variable "ambiente" {
  description = "Environment name. Determines hardening posture (prod-like vs dev-like)."
  type        = string

  validation {
    condition     = contains(["dev", "qa", "preprod", "prod", "dr"], var.ambiente)
    error_message = "ambiente must be one of: dev, qa, preprod, prod, dr."
  }
}

variable "aws_account_id" {
  description = "Target AWS account ID (12-digit). All resources deploy into this account."
  type        = string

  validation {
    condition     = can(regex("^[0-9]{12}$", var.aws_account_id))
    error_message = "aws_account_id must be a 12-digit AWS account ID."
  }
}

# ═══════════════════════════════════════════════════════════════════════════════
# MANDATORY CORPORATE TAGS (passed through to ALL building blocks)
# ═══════════════════════════════════════════════════════════════════════════════

variable "aplicacion" {
  description = "Application name (mandatory corporate tag)."
  type        = string

  validation {
    condition     = length(var.aplicacion) >= 3 && !contains(["XXXX", "TBD", "CHANGEME", "TODO"], upper(var.aplicacion))
    error_message = "aplicacion must be at least 3 chars and not a placeholder."
  }
}

variable "propietario_recurso" {
  description = "Resource owner (mandatory corporate tag)."
  type        = string

  validation {
    condition     = length(var.propietario_recurso) >= 3 && !contains(["XXXX", "TBD", "CHANGEME", "TODO"], upper(var.propietario_recurso))
    error_message = "propietario_recurso must be at least 3 chars and not a placeholder."
  }
}

variable "producto" {
  description = "Product name (mandatory corporate tag)."
  type        = string

  validation {
    condition     = length(var.producto) >= 3 && !contains(["XXXX", "TBD", "CHANGEME", "TODO"], upper(var.producto))
    error_message = "producto must be at least 3 chars and not a placeholder."
  }
}

variable "centro_costo" {
  description = "Cost center (mandatory corporate tag)."
  type        = string

  validation {
    condition     = length(var.centro_costo) >= 3 && !contains(["XXXX", "TBD", "CHANGEME", "TODO"], upper(var.centro_costo))
    error_message = "centro_costo must be at least 3 chars and not a placeholder."
  }
}

variable "extra_tags" {
  description = "Additional tags to merge with the mandatory set. Applied to all building blocks."
  type        = map(string)
  default     = {}
}

# ═══════════════════════════════════════════════════════════════════════════════
# AURORA POSTGRESQL
# ═══════════════════════════════════════════════════════════════════════════════

variable "aurora_enabled" {
  description = "Enable the Aurora PostgreSQL building block."
  type        = bool
  default     = false
}

variable "aurora_config" {
  description = <<-EOT
    Configuration for Aurora PostgreSQL cluster.
    Only evaluated when aurora_enabled = true.

    Example:
      {
        engine_version    = "16.6"
        serverless        = true
        min_acu           = 0.5
        max_acu           = 4
        database_name     = "appdb"
        instance_class    = "db.serverless"
        instances         = {}
      }
  EOT
  type = object({
    engine_version  = optional(string, "16.6")
    db_family       = optional(string, "")
    database_name   = optional(string, "")
    master_username = optional(string, "svcadmin")
    serverless      = optional(bool, true)
    min_acu         = optional(number, 0.5)
    max_acu         = optional(number, 4)
    instance_class  = optional(string, "db.serverless")
    storage_type    = optional(string, "standard")
    multi_az        = optional(bool, null)
    instances = optional(map(object({
      instance_class = optional(string)
      az             = optional(string, "a")
      promotion_tier = optional(number, 1)
    })), {})
    allowed_security_group_ids = optional(list(string), [])
    allowed_cidrs = optional(list(object({
      description = string
      cidr        = string
    })), [])
    backup_retention_period       = optional(number, null)
    deletion_protection           = optional(bool, null)
    apply_immediately             = optional(bool, null)
    performance_insights_enabled  = optional(bool, true)
    enable_global_database        = optional(bool, false)
    global_cluster_identifier     = optional(string, "")
    kms_key_alias                 = optional(string, "alias/RDS")
    kms_key_arn                   = optional(string, "")
    cloudwatch_logs_kms_key_alias = optional(string, "alias/CWLogs")
    cloudwatch_logs_kms_key_arn   = optional(string, "")
  })
  default = {}
}

# ═══════════════════════════════════════════════════════════════════════════════
# SQS
# ═══════════════════════════════════════════════════════════════════════════════

variable "sqs_enabled" {
  description = "Enable the SQS building block."
  type        = bool
  default     = false
}

variable "sqs_queues" {
  description = <<-EOT
    Map of SQS queues to create. Each queue gets a mandatory DLQ.
    Only evaluated when sqs_enabled = true.

    Example:
      {
        notificaciones = {
          fifo                       = false
          visibility_timeout_seconds = 30
          message_retention_days     = 7
        }
        pagos = {
          fifo                        = true
          content_based_deduplication = true
        }
      }
  EOT
  type = map(object({
    fifo                        = optional(bool, false)
    visibility_timeout_seconds  = optional(number, 30)
    message_retention_days      = optional(number, 4)
    max_message_size_bytes      = optional(number, 262144)
    delay_seconds               = optional(number, 0)
    receive_wait_time_seconds   = optional(number, 20)
    content_based_deduplication = optional(bool, false)
    dlq_max_receive_count       = optional(number, 3)
    dlq_message_retention_days  = optional(number, 14)
  }))
  default = {}

  validation {
    condition     = alltrue([for k, _ in var.sqs_queues : can(regex("^[a-z0-9-]+$", k))])
    error_message = "Queue keys must be lowercase alphanumeric and hyphens only."
  }
}

variable "sqs_config" {
  description = <<-EOT
    Additional SQS configuration (KMS, etc.).
    Only evaluated when sqs_enabled = true.
  EOT
  type = object({
    kms_key_alias                     = optional(string, "alias/SQS_SNS")
    kms_key_arn                       = optional(string, "")
    kms_data_key_reuse_period_seconds = optional(number, 300)
  })
  default = {}
}

# ═══════════════════════════════════════════════════════════════════════════════
# ELASTICACHE SERVERLESS (REDIS / VALKEY)
# ═══════════════════════════════════════════════════════════════════════════════

variable "redis_enabled" {
  description = "Enable the ElastiCache Serverless building block."
  type        = bool
  default     = false
}

variable "redis_config" {
  description = <<-EOT
    Configuration for ElastiCache Serverless cache.
    Only evaluated when redis_enabled = true.

    Example:
      {
        engine               = "valkey"
        major_engine_version = "8"
        max_ecpu_per_second  = 5000
        max_data_storage_gb  = 5
      }
  EOT
  type = object({
    engine                     = optional(string, "valkey")
    major_engine_version       = optional(string, "8")
    max_ecpu_per_second        = optional(number, null)
    max_data_storage_gb        = optional(number, null)
    snapshot_retention_days    = optional(number, null)
    daily_snapshot_time        = optional(string, null)
    allowed_security_group_ids = optional(list(string), [])
    allowed_cidrs = optional(list(object({
      description = string
      cidr        = string
    })), [])
    user_group_id = optional(string, "")
    kms_key_alias = optional(string, "alias/ElastiCache")
    kms_key_arn   = optional(string, "")
  })
  default = {}
}

# ═══════════════════════════════════════════════════════════════════════════════
# IRSA (IAM ROLES FOR SERVICE ACCOUNTS)
# ═══════════════════════════════════════════════════════════════════════════════

variable "irsa_enabled" {
  description = "Enable the IRSA building block."
  type        = bool
  default     = false
}

variable "irsa_config" {
  description = <<-EOT
    Configuration for IRSA roles. The oidc_issuer_url is required when
    irsa_enabled = true.

    Example:
      {
        oidc_issuer_url = "rh-oidc.s3.us-east-1.amazonaws.com/2raaaq28u2u..."
      }
  EOT
  type = object({
    oidc_issuer_url = optional(string, "")
  })
  default = {}
}

variable "irsa_roles" {
  description = <<-EOT
    Map of IRSA roles to create. Keys become role name suffixes.
    Only evaluated when irsa_enabled = true.

    Each role maps to ONE Kubernetes ServiceAccount and gets policies
    that may reference outputs from other building blocks (native deps).

    Example:
      {
        api-consumer = {
          namespace       = "bff-personas"
          service_account = "bff-sa"
          policies = {
            aurora_connect = true
            sqs_full       = true
            redis_connect  = true
          }
          extra_inline_policies   = {}
          extra_managed_policy_arns = []
        }
      }
  EOT
  type = map(object({
    namespace       = string
    service_account = string
    description     = optional(string, "")
    policies = optional(object({
      aurora_connect = optional(bool, false)
      sqs_full       = optional(bool, false)
      redis_connect  = optional(bool, false)
    }), {})
    extra_inline_policies     = optional(map(string), {})
    extra_managed_policy_arns = optional(list(string), [])
    permission_boundary_arn   = optional(string, "")
    max_session_duration      = optional(number, 3600)
  }))
  default = {}

  validation {
    condition     = alltrue([for k, _ in var.irsa_roles : can(regex("^[a-z0-9-]+$", k))])
    error_message = "IRSA role keys must be lowercase alphanumeric and hyphens only."
  }
}

# ═══════════════════════════════════════════════════════════════════════════════
# SECRETS (injected from BeyondTrust via TF_VAR_*)
# ═══════════════════════════════════════════════════════════════════════════════

variable "master_password" {
  description = "Aurora admin password. SENSITIVE — injected by ci.yml as TF_VAR_master_password from BeyondTrust Secrets Safe. Required when aurora_enabled = true."
  type        = string
  default     = ""
  sensitive   = true
}
